// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaLaura.DAL.DAL;

#nullable disable

namespace TiendaLaura.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TiendaLaura.Models.TiendaLaura.Entities.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"), 1L, 1);

                    b.Property<string>("NombreColor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Colores");
                });

            modelBuilder.Entity("TiendaLaura.Models.TiendaLaura.Entities.Prenda", b =>
                {
                    b.Property<int>("PrendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrendaId"), 1L, 1);

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombrePrenda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoPrendaId")
                        .HasColumnType("int");

                    b.HasKey("PrendaId");

                    b.HasIndex("ColorId");

                    b.HasIndex("TipoPrendaId");

                    b.ToTable("Prendas");
                });

            modelBuilder.Entity("TiendaLaura.Models.TiendaLaura.Entities.TipoPrenda", b =>
                {
                    b.Property<int>("TipoPrendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoPrendaId"), 1L, 1);

                    b.Property<string>("TipoPrendaNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoPrendaId");

                    b.ToTable("TiposPrenda");
                });

            modelBuilder.Entity("TiendaLaura.Models.TiendaLaura.Entities.Prenda", b =>
                {
                    b.HasOne("TiendaLaura.Models.TiendaLaura.Entities.Color", "Color")
                        .WithMany("Prendas")
                        .HasForeignKey("ColorId");

                    b.HasOne("TiendaLaura.Models.TiendaLaura.Entities.TipoPrenda", "TipoPrenda")
                        .WithMany("Prendas")
                        .HasForeignKey("TipoPrendaId");

                    b.Navigation("Color");

                    b.Navigation("TipoPrenda");
                });

            modelBuilder.Entity("TiendaLaura.Models.TiendaLaura.Entities.Color", b =>
                {
                    b.Navigation("Prendas");
                });

            modelBuilder.Entity("TiendaLaura.Models.TiendaLaura.Entities.TipoPrenda", b =>
                {
                    b.Navigation("Prendas");
                });
#pragma warning restore 612, 618
        }
    }
}
